### ISSUE TITLE
Issue: ❓ Support Question

### ISSUE THREAD

**Issue by Theolodewijk** [tg-bot-api/bot-api-base#23]
I tray to get some info bot Telegram don't reply support tickets!

Can you help me with Telegram. so that I am sent in the right direction.

I work for a government organization and we have a weekly exercise, now I would like to simplify this with, for example, a poll or something else where if someone responds to that I get a feedback via the telegram API.

I want to use PHP for this but see many options on the Telegram website https://core.telegram.org/bots/samples#php but now which one is and is not suitable for this and there is a little explanation somewhere how to find it tackles this?

https://telegram.org/blog/polls-2-0-vmq

Greetings Theo

**Comment by Big-Shark** [comment]
Hi @Theolodewijk 

I hope this helps you, this is a simple script send poll in a chat room.

```
$botKey = '<bot key>';

$requestFactory = new Http\Factory\Guzzle\RequestFactory();
$streamFactory = new Http\Factory\Guzzle\StreamFactory();
$client = new Http\Adapter\Guzzle6\Client();

$apiClient = new \TgBotApi\BotApiBase\ApiClient($requestFactory, $streamFactory, $client);
$bot = new \TgBotApi\BotApiBase\BotApi($botKey, $apiClient, new \TgBotApi\BotApiBase\BotApiNormalizer());

$chatId = '<user id>';

$bot->send(SendPollMethod::create($chatId, 'question', ['v1', 'v2']));
```

If you need more information, please, ask me or @greenplugin , and we can try help you.

**Comment by greenplugin** [comment]
Also you can use SendPoolMethod as it described in official api:
https://core.telegram.org/bots/api#sendpoll
and receive updates in webhooks like this: 
```php 
$fetcher = new \TgBotApi\BotApiBase\WebhookFetcher(new \TgBotApi\BotApiBase\BotApiNormalizer());
$update = $fetcher->fetch(file_get_contents('php://input'));
$pool = $update->poll;
```
'poll' property of update will contain poll object as is in documentation
https://core.telegram.org/bots/api#poll

Also you can use GetUpdates method to get updates without webhook
