### ISSUE TITLE
Poll data is absent in MessageType class

### ISSUE THREAD

**Issue by glukkkk** [tg-bot-api/bot-api-base#24]
When sending **SendPollMethod**, there is no poll info in response. I suppose it can be achieved by adding the following property to the **MessageType** class:

```php
    /**
     * @var PollType
     */
    public $poll;
```

I rely on a quick fix for this. Thank you in advance.

**Comment by greenplugin** [comment]
Hey! Good point! Thanks! We will fix it today.

**Comment by greenplugin** [comment]
This bug fixed in #25 pr. New version released.
Thanks for this issue!

**Comment by glukkkk** [comment]
Super fast! Thanks!
