### ISSUE TITLE
[InvalidArgumentException] Could not find a matching version of package greenplugin/telegram-bot-api.      Check the package spelling, your version constraint and that the package is      available in a stability which matches your minimum-stability (stable).

### ISSUE THREAD

**Issue by virupakkha** [tg-bot-api/bot-api-base#3]
## Detailed description

When I tried to install using composer, I got this error message : 

> [InvalidArgumentException]                                                   
>   Could not find a matching version of package greenplugin/telegram-bot-api.   
>   Check the package spelling, your version constraint and that the package is  
>    available in a stability which matches your minimum-stability (stable).

Installation does not work because there are no stable version. Please make a release so it can be used.

**Comment by greenplugin** [comment]
it was an error in readme, you can use 
```bash 
composer require tg-bot-api/bot-api-base
```
Besides I updated readme and version of the package to 1.x
