### ISSUE TITLE
BotApi::edit(EditMessageMediaMethod) cast error

### ISSUE THREAD

**Issue by ali-dahaghin** [tg-bot-api/bot-api-base#39]
after executing following line:

```php
BotApi::edit(EditMessageMediaMethod::create($chatId, $messageId, InputMediaVideoType::create($url), array('replyMarkup'=>$someInlineKeyboardMarkup)));
```

exception throws : ```Bad Request: can't parse InputMedia: Can't parse media JSON object```

and PHP Notice : ```Array to string conversion in /foo/vendor/tg-bot-api/bot-api-base/src/ApiClient.php on line 106``` which is ApiClient::createStreamBody() method

**Comment by greenplugin** [comment]
Hi, thanks for the issue. I'll fix it today.

**Comment by greenplugin** [comment]
Can you show more code? Is your replyMarkup instance one of InlineKeyboardMarkupType|ReplyKeyboardMarkupType|ReplyKeyboardRemoveType|ForceReplyType?

**Comment by greenplugin** [comment]
I think we can create Type hinting for not required prarms in conctructor.  @Big-Shark, what dou think about it?

**Comment by Big-Shark** [comment]
@greenplugin yeah, this is good idia.

**Comment by ali-dahaghin** [comment]
```replyMarkup``` is instance of ```InlineKeyboardMarkupType```

this ```replyMarkup``` works in other methods like sending photo.

I think the problem is for ```InputMedia``` which can't be casted to string in ApiClient line 106.
so instead of casting maybe it is possible to convert it to string.

code:
```php
$inlineKeyboardButtons[] = array(InlineKeyboardButtonType::create($keys['prev']['text'], $keys['prev']['data']), InlineKeyboardButtonType::create($keys['next']['text'], $keys['next']['data']));
$inlineKeyboardButtons[] = array(InlineKeyboardButtonType::create($keys['jumpTo']['text'], $keys['jumpTo']['data']));
$replyMarkup = InlineKeyboardMarkupType::create($inlineKeyboardButtons);

$caption = 'foobar';

$inputMedia = InputMediaVideoType::create($result->getVideoUrl(), array('caption'=>$caption)); // or without caption still result is the same

$bot->edit(EditMessageMediaMethod::create($chatId, $messageId, $inputMedia, array('replyMarkup'=>$replyMarkup)));
```

all values are valid in code

**Comment by greenplugin** [comment]
Oh, yeah, You're right. It happens because InputMedia doesn't serialize correctly, I'll fix it in next few hours.

**Comment by greenplugin** [comment]
Done. Please update your package to 1.6.2 version.

**Comment by ali-dahaghin** [comment]
thanks
