### ISSUE TITLE
EditMessage Problem

### ISSUE THREAD

**Issue by LanKing** [tg-bot-api/bot-api-base#4]
$response = $bot->send(
            \TgBotApi\BotApiBase\Method\SendMessageMethod::create($userId, 'Hi2')
        );

        $prevMessageId = $response->messageId;
        $response = $bot->edit(
            \TgBotApi\BotApiBase\Method\EditMessageTextMethod::create($userId, $prevMessageId, 'Hello')
        );

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 3 passed to TgBotApi\BotApiBase\ApiClient::createDataStream() must be of the type string, int given

**Comment by LanKing** [comment]
Проблему вызвал message_id. 
Сделал приведение типа:
$stream .= $this->createDataStream($boundary, $name, (string)$value);

Но обнаружил что проблема шире, а именно: edit возвращает stdClass а не bool, как декларировано

**Comment by greenplugin** [comment]
Thanks for feedback. I have fixed this issues in [1.0.1](https://github.com/tg-bot-api/bot-api-base/tree/1.0.1)
