### ISSUE TITLE
PHP 7 Support?

### ISSUE THREAD

**Issue by ErikThiart** [tg-bot-api/bot-api-base#5]
Could not find package tg-bot-api/bot-api-base at any version matching your PHP version 7.0.10.0

Do you support PHP7?

**Comment by Big-Shark** [comment]
@ErikThiart Hi, we support minimum php7.2
https://github.com/tg-bot-api/bot-api-base/blob/master/composer.json#L26

**Comment by ErikThiart** [comment]
Shit. Lol - I will upgrade :)
