### ISSUE TITLE
Баг нормализации InlineKeyboardMarkupType

### ISSUE THREAD

**Issue by Inogami** [tg-bot-api/bot-api-base#52]
## Описание
Telegram ожидает в поле reply_markup json с ключом inline_keyboard и значением в виде массива массивов, но после нормализации в reply_markup остается json c ключом inline_keyboard значения которого массив объектов

PHP 7.4.2
Slim 4.7

**Comment by greenplugin** [comment]
I'll check and fix the issue this weekend. 
Or you can make a pull request.

**Comment by Inogami** [comment]
Sorry, everything work just fine. I'm misread documentation
