### ISSUE TITLE
Create symfony flex recipe

### ISSUE THREAD

**Issue by greenplugin** [tg-bot-api/bot-api-base#9]
We need to create Symfony Flex recipe for this library.
It will easy installation and easy configuration.

**Comment by Big-Shark** [comment]
I created PR, https://github.com/symfony/recipes-contrib/pull/805, but we have a problem with tests

**Comment by greenplugin** [comment]
We need to fix it and add options for web client selection if it already not defined in a project

**Comment by Big-Shark** [comment]
Merged https://github.com/symfony/recipes-contrib/pull/805
